# ~/.config/starship.toml
format = """
$conda\
$username\
$hostname\
$directory\
$container\
$git_branch\
$git_status\
$cmd_duration\
$line_break\
$character"""

add_newline = true

[conda]
ignore_base = false
style = "white"
format = '[\($environment\)]($style) '

[username]
show_always = true
style_user = "bold fg:green"
format = '[$user]($style)'

[hostname]
style = "bold fg:green"
format = '@[$hostname]($style)'

[directory]
truncation_length = 8
truncation_symbol = ".../"
truncate_to_repo = false
style = "bold fg:green"
format = ":[$path]($style) "

[container]
style = "bold blue"
format = '[$symbol]($style) '

[fill]
symbol = " "

[cmd_duration]
style = "yellow"
format = "took [$duration]($style) "
